# Final Response

In [ ]:
# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape
}

# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = np.add(u,v)             # u+v
u_minus_v = np.subtract(u,v)       # u-v
alpha_times_u = np.array(u)*alpha  # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)              # u . v
norm_u = np.linalg.norm(u)         # ||u|| 


# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None                                     # A + C
A_minus_Ctranspose = np.subtract(A,C.transpose())   # A - C.T
Ctranspose_plus_3D = np.add(C.transpose(),D*3)      # C.T + 3*D
B_times_A = np.matmul(B,A)                          # B*A
B_times_Atranspose = None                           # B*A.T

# Q4: (bonus)

B_times_C = None                                    # B*C
C_times_B = np.matmul(C,B)                          # C*B
B_exp_4 = np.linalg.matrix_power(B, 4)              # B^4
A_times_Atranspose = np.matmul(A,A.transpose())     # A*A.T
Dtranspose_times_D = np.matmul(D.transpose(),D)     # D.T*D

# Scratch Work

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

## Q1

In [3]:
# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape
}


In [4]:
dimensions

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (4,), 'v': (4,)}

## Q2

In [6]:
# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = np.add(u,v)            # u+v
print(u_plus_v)

[ 9  7 -4  9]


In [7]:
u_minus_v = np.subtract(u,v)           # u-v
print(u_minus_v)

[ 3 -3 -2  1]


In [12]:
alpha_times_u = np.array(u)*alpha      # alpha * u, alpha = 6 
print(alpha_times_u)

[ 36  12 -18  30]


In [13]:
u_dot_v = np.dot(u,v)   # u . v
print(u_dot_v)

51


In [14]:
norm_u = np.linalg.norm(u)   # ||u||
print(norm_u)

8.602325267042627


## Q3

In [15]:
# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = np.add(A,C)             # A + C
print(A_plus_C)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [16]:
A_minus_Ctranspose = np.subtract(A,C.transpose())   # A - C.T
print(A_minus_Ctranspose)

[[-4 -7 -3]
 [ 3  6  4]]


In [17]:
Ctranspose_plus_3D = np.add(C.transpose(),D*3)   # C.T + 3*D
print(Ctranspose_plus_3D)

[[14  3  3]
 [ 2  7  9]]


In [18]:
B_times_A = np.matmul(B,A)            # B*A
print(B_times_A)

[[-1 -5 -1]
 [ 2  7  4]]


In [19]:
B_times_Atranspose = np.matmul(B,A.transpose())   # B*A.T
print(B_times_Atranspose)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)